version: '2'
services:
  web:
    build: .
    image: garcianavalon/hellostripe
    environment:
      - DEBUG=hellostripe:*
      - STRIPE_API_KEY=pk_test_EUkfRZwz4TXS3ujwC4GNRIUy
    volumes:
      - .:/app
      - /app/node_modules
    command: [nodemon, ./bin/www]
    ports:
      - "3000:3000"

