version: '2'
services:
  web:
    build: .
    image: garcianavalon/hellostripe
    environment:
      - DEBUG=hellostripe:*
    volumes:
      - .:/app
      - /app/nodevolumes
    command: [nodemon, ./bin/www]
    ports:
      - "3000:3000"

